### ISSUE TITLE
Set up our Kanban board

### ISSUE THREAD

**Issue by dfsalam** [dfsalam/catalog-of-my-things#18]
https://github.com/dfsalam/catalog-of-my-things/projects/1

Hello, we are 3 people on our team.
- Team member 1: @biruk-bereka 
- Team member 2 @dfsalam 
- Team member 3 @kensteph

**Comment by OyePriscilla** [comment]
Hi @dfsalam, @kensteph and @biruk-bereka 👏 👏 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights


## Required Changes ♻️

- [ ] **Kindly assign these missing group tasks to any member of the group fairly**. 👇 
<img width="801" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/234119352-de31abfa-bf1c-4d5b-8048-ac92a0e9d0ef.png">

- [ ] **Please kindly take note that the title of most of your tasks supposed to be part of the tasks description according to the project requirement.** 👇 
<img width="255" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/234119825-e64afdfd-664e-4c40-8b9a-06d3e589cc62.png"> **Note: You will need to apply this correction to almost of your tasks**

- [ ] **Please ensure that there is no empty description for all the tasks to be implemented, example of one of your tasks with empty description** 👇 
<img width="253" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/234120513-42b41db7-21bf-42ec-bed5-14426f86897d.png">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omar-muhamad** [comment]
# Approved ✔
### Hi Team,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to close this issue and start working on the project :shipit: 

### GOOD LUCK 🤞 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
